#
# Module manifest for module 'IdentityCommand.AccessRequest'
#
# Generated by: Pete Maan
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'IdentityCommand.AccessRequest.psm1'

    # Version number of this module.
    ModuleVersion     = '0.0'

    # ID used to uniquely identify this module
    GUID              = '83f93778-98fc-452e-9650-767c37e9e806'

    # Author of this module
    Author            = 'Pete Maan'

    # Company or vendor of this module
    CompanyName       = 'PSPETE'

    # Copyright statement for this module
    Copyright         = '(c) Pete Maan. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Enables user interaction with the Access Request API for Idira (CyberArk)'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @(
        @{ModuleName = 'IdentityCommand'; GUID = 'f6bb2bdf-0c53-443f-be07-3c25264a09b1'; ModuleVersion = '0.7.159' }
    )

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Connect-ARTenant',
        'Get-ARModuleData',
        'Get-ARRequest',
        'Get-ARRequestForm',
        'New-ARRequest',
        'Stop-ARRequest',
        'Approve-ARRequest',
        'Deny-ARRequest'
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @('CyberArk', 'CyberArk-API', 'REST', 'API', 'Idira', 'Idira-API', 'Idira-REST', 'Access-Request', 'Approval', 'Workflow')

            # A URL to the license for this module.
            LicenseUri   = 'https://github.com/pspete/IdentityCommand.AccessRequest/blob/main/LICENSE.md'

            # A URL to the main website for this project.
            ProjectUri   = 'https://github.com/pspete/IdentityCommand.AccessRequest/'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/pspete/IdentityCommand.AccessRequest/blob/main/CHANGELOG.md'

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
